# Generated by Django 6.1.1 on 2026-09-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default='10:00')),
                ('closing_time', models.TimeField(default='23:00')),
            ],
            options={
                'verbose_name': 'Academy Settings',
                'verbose_name_plural': 'Academy Settings',
            },
        ),
    ]
