# Generated by Django 6.1.1 on 2026-09-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coaching Content',
                'verbose_name_plural': 'Coaching Content',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
