# Generated by Django 6.1.1 on 2026-09-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_coachingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Membership Content',
                'verbose_name_plural': 'Membership Content',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
