# Generated by Django 6.1.1 on 2026-09-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_membershipcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tournament_date', models.DateField(blank=True, null=True)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prize_info', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tournament Content',
                'verbose_name_plural': 'Tournament Content',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
