# Generated by Django 6.1.1 on 2026-09-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentcontent',
            options={'ordering': ['display_order', 'tournament_date', 'id'], 'verbose_name': 'Tournament Content', 'verbose_name_plural': 'Tournament Content'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_intro',
            field=models.TextField(blank=True, default='Have a question about table bookings, coaching, memberships or tournaments? Get in touch with us.'),
        ),
    ]
