# Generated by Django 6.1.1 on 2026-09-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_tournamentcontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Premium Snooker Experience', max_length=200)),
                ('hero_description', models.TextField(default='Experience premium snooker tables, professional coaching and a welcoming environment at Royal Snooker Academy.')),
                ('introduction_title', models.CharField(default='Welcome to Royal Snooker Academy', max_length=200)),
                ('introduction_text', models.TextField(default='Royal Snooker Academy provides a professional and comfortable environment for players of all skill levels.')),
                ('featured_title', models.CharField(default='Everything You Need to Play Better', max_length=200)),
                ('featured_text', models.TextField(default='Book premium tables, improve your game with professional coaching, participate in tournaments and enjoy a great snooker experience.')),
                ('tables_stat', models.PositiveIntegerField(default=5)),
                ('coaching_stat', models.CharField(default='Professional', max_length=50)),
                ('tournaments_stat', models.CharField(default='Regular', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
    ]
