# Generated by Django 6.1.1 on 2026-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_amount_alter_booking_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingcontent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
