# Generated by Django 6.1.1 on 2026-10-03 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_bookingemailnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEmailDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='sending', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='bookings.bookingemailnotification')),
            ],
            options={
                'ordering': ['-attempt_number'],
                'constraints': [models.UniqueConstraint(fields=('notification', 'attempt_number'), name='booking_email_attempt_number_uniq')],
            },
        ),
    ]
