# Generated by Django 6.1.1 on 2026-10-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_bookingemaildeliveryattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('requested_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, choices=[('plans_changed', 'My plans changed'), ('booked_wrong_details', 'I selected the wrong date or time'), ('unable_to_attend', 'I can no longer attend'), ('booked_by_mistake', 'I made this booking by mistake'), ('other', 'Other')], max_length=32)),
                ('reason_details', models.CharField(blank=True, max_length=500)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cancellation', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Customer Cancellation',
                'verbose_name_plural': 'Customer Cancellations',
            },
        ),
    ]
